### ISSUE TITLE
Add validation to model constructors

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/scala-play-car-advert#10]
For both models we can do validation on the constructor by using something like

http://stackoverflow.com/questions/20478588/scala-case-class-how-to-validate-constructors-parameters

Then we can see if we return `Option/Maybe` or `Try`

**Update:** Better to use `Try` to handle possible validation exceptions

http://danielwestheide.com/blog/2012/12/26/the-neophytes-guide-to-scala-part-6-error-handling-with-try.html

**Comment by inakianduaga** [comment]
# TODO:
- [x] The validation method should return a Try[None] instead of a boolean, where the exception is wrapped. That way we can propagate the exception so we know what the validation error was
  - All validation methods should return Try[None], each one should add an exception error message
  - Flatten Try collection using http://stackoverflow.com/questions/15495678/flatten-scala-try so we get a Try[Collection] with the possible validation errors

**Comment by inakianduaga** [comment]
- [x] Factor out shared validation logic into Trait method
- [x] Write unit tests to check validation logic
