### ISSUE TITLE
Controller data flow

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/scala-play-car-advert#14]
The data flow is

```
controller (raw json) -> `hydrated CarAdvert` -> StorageDriverTrait -> StorableTypeTrait -> `hydratedCarAdvert`  -> raw json
```
# Json service
- [x] We need some logic to convert from the raw input json into an `Either[AdvertNewCar,AdvertUsedCar]`. If we do that then it becomes easy to 
- [x] We need logic to convert to raw json.
- [x] Write tests for the Json service
# Hydrate Service

We need a service that will  hydrate/convert between the database `StorableTrait` input/output types and the `AdvertNewCar/AdvertUsedCar` types.

Service needs to:
- [x] Given a StorableType, it needs to convert it into an Either[AdvertNewCar,AdvertUsedCar]. The other direction is already satisfied, since the `AdvertNewCar,AdvertUsedCar` already implement StorableType.

**Comment by inakianduaga** [comment]
# TODO:
- [x] Get Guice dependency injection working for the DynamoDB storage service
- [x] Fix DynamoDB initialization failing
- [x] Test controller index method manually
