### ISSUE TITLE
Scala database code structure

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/scala-play-car-advert#7]
# Idea:

The following is  brainstorming how to best setup the database access layer
- `StorageDriverTrait`: An interface that has CRUD `get/delete/update/create` methods and
  -  takes the full models Either(CarAdvertNew|CarAdvertUsed) as parameters. 
    -This will return the same for the getter methods (with an optional collection). The actual storage format is invisible to the user.
- `DynamoDbStorage`: The actual implementation, constructs JSON from each of the models (the modes I guess should have a toJson method), and an object companion fromJson probably as well

**Comment by inakianduaga** [comment]
# TODO:
- [x] Add a `toJson` method on the models that can be used by DynamoDB for storage
- [x] Type `StorableTrait` as an interface that has a type and a `toJson` method that we can use to store in dynamoDB.
- [x] Storage Driver should depend on a generic only and return the same generic of type `StorableTrait` (See http://stackoverflow.com/questions/20508529/subtype-in-scala-what-is-type-x-y)
- [x] Setup DynamoDB sdk

**Comment by inakianduaga** [comment]
# TODO:
- [ ] Add tests for dynamoDB, for this we need to be able to run a script before the test w/ DynamoDB running locally (launched with a container) if it doesn't exist

**Update: We can't seem to get the DB tests going because we can't bootstrap the configuration since dependency injection doesn't seem to work**
